"""
Django settings for tvt project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path #-> Asegúrate de que BASE_DIR está definido con pathlib
from decouple import config, Csv
from pathlib import Path
import os
import pymysql
pymysql.install_as_MySQLdb()
from django.utils.translation import gettext_lazy as _

ADMINS = [('Tavata', 'tavata.art@outlook.com')]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# 1. Leer la variable de entorno principal.
#    Por seguridad, si no se define, se asume 'production'.
ENVIRONMENT = config('ENVIRONMENT', default='development', cast=str)

print("*********************************************")
print(f"**** EJECUTANDO EN AMBIENTE: {ENVIRONMENT.upper()} ****")
print("*********************************************")

# 2. Configurar otras variables basadas en el ambiente
if ENVIRONMENT == 'development':
    SECRET_KEY = config('SECRET_KEY', default='django-insecure-dev-key-default')
    DEBUG = True
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else: # Para 'testing', 'production' u otros
    SECRET_KEY = config('SECRET_KEY')
    # DEBUG es False por defecto, a menos que un ambiente específico lo active
    DEBUG = config('DEBUG', default=False, cast=bool)
    ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv()) #-> Permite múltiples hosts separados por comas
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Application definition

INSTALLED_APPS = [
    # 1. modeltranslation PRIMERO. Esto asegura que su "magia" de
    #    parcheo y registro se ejecute antes que cualquier otra cosa,
    #    especialmente antes que el 'admin'.
    'modeltranslation',

    # 2. Las apps de Django Core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # 3. Otras apps de Terceros
    'django_summernote',
    'solo',
    'mptt',
    'taggit',
    'parler',

    # 4. Nuestras Propias Aplicaciones
    'core.apps.CoreConfig',
    'pages.apps.PagesConfig',
    'blog.apps.BlogConfig',
    'menus.apps.MenusConfig', 
    'site_settings.apps.SiteSettingsConfig', 
    'search.apps.SearchConfig', 
    'contact.apps.ContactConfig',
    'widgets.apps.WidgetsConfig',
    'accounts.apps.AccountsConfig',
    'categories.apps.CategoriesConfig',
    'gallery.apps.GalleryConfig',
    'testimonials',
    'posts',
    'tags',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # <-- ¡Localization!
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tvt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'tvt.context_processors.languages_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'tvt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 3. Configurar la base de datos basada en el ambiente
# Primero, la configuración por defecto para desarrollo
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Luego, sobrescribimos si estamos en un ambiente de tipo MySQL
if ENVIRONMENT == 'testing' or ENVIRONMENT == 'production':
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }


# --- CACHING CONFIGURATION ---
# https://docs.djangoproject.com/en/5.2/topics/cache/
CACHES = {
    'default': {
        # In-memory cache for development. Fast but resets with every server restart.
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'tavata-cms-unique-cache',
    }
}

# Para producción, podríamos usar algo más robusto como Redis:
# 'default': {
#     'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#     'LOCATION': 'redis://127.0.0.1:6379/1',
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Idioma por defecto
LANGUAGE_CODE = 'en' 

# Lista de idiomas disponibles
LANGUAGES = [
    ('es', _('Español')),
    ('en', _('English')),
    ('ca', _('Català')),
]

PARLER_LANGUAGES = {
    None: (
        {'code': 'es'},
        {'code': 'en'},
        {'code': 'ca'},
    ),
    'default': {
        'fallbacks': ['es'],
        'hide_untranslated': False,
        'redirect_on_fallback': False,
    }
}
PARLER_ENABLE_CACHING = False 

# Rutas donde Django buscará los archivos de traducción (.po/.mo)
LOCALE_PATHS = [
    BASE_DIR / 'locale/',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# La ruta donde `collectstatic` copiará todos los archivos para producción.
# Es bueno tenerla definida aunque en desarrollo no se use directamente.
STATIC_ROOT = BASE_DIR / 'staticfiles'
if ENVIRONMENT == 'production':
    STATIC_ROOT = "/home/sextavac/domains/tavata.art/public_html/static"

# ¡LA CONFIGURACIÓN CLAVE PARA DESARROLLO!
# Directorios adicionales donde el servidor de desarrollo de Django buscará archivos estáticos.
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
if ENVIRONMENT == 'production':
    MEDIA_ROOT = "/home/sextavac/domains/tavata.art/public_html/media"

X_FRAME_OPTIONS = 'SAMEORIGIN'

# ==============================================================================
# LOGGING CONFIGURATION
# ==============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False, # No desactiva los loggers por defecto de Django

    # --- FORMATTERS: Cómo se verá cada línea del log ---
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },

    # --- FILTERS: Para añadir contexto o filtrar logs ---
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },

    # --- HANDLERS: A dónde se envía cada log (consola, archivo, email) ---
    'handlers': {
        # Handler para la consola de desarrollo
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'], # Solo funciona si DEBUG=True
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        # Handler para guardar en un archivo los warnings y errores
        'file_error': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs/error.log', # Ruta al archivo
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 2,
            'formatter': 'verbose',
        },
        # Handler para que los administradores reciban un email en caso de error 500
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'], # Solo funciona si DEBUG=False
            'class': 'django.utils.log.AdminEmailHandler',
        },
    },

    # --- LOGGERS: El cerebro que une todo ---
    'loggers': {
        # Logger principal de Django. Capturará todo lo que pase en el framework.
        'django': {
            'handlers': ['console', 'file_error', 'mail_admins'],
            'level': 'INFO',
            'propagate': True,
        },
        # Podemos crear loggers para nuestras propias apps si queremos
        # 'blog': {
        #     'handlers': ['console', 'file_error'],
        #     'level': 'DEBUG',
        # },
    },
}

# URL to redirect to after a successful login.
LOGIN_REDIRECT_URL = '/'

# URL to redirect to after a successful logout.
LOGOUT_REDIRECT_URL = '/'