# Generated by Django 5.2.3 on 2025-06-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags assigned to this post. Managed via TaggedPost intermediate model.', related_name='posts', through='tags.TaggedPost', to='tags.tag', verbose_name='Tags'),
        ),
    ]
