# Generated by Django 5.2.3 on 2025-06-29 21:01

import django.db.models.deletion
import django.utils.timezone
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_post_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=100, verbose_name='Author Name')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='Author Email')),
                ('content', models.TextField(verbose_name='Content')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Original Language')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is Approved?')),
                ('translated_content', models.TextField(blank=True, null=True, verbose_name='Translated Content')),
                ('translation_language', models.CharField(blank=True, max_length=10, null=True, verbose_name='Translation Language')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comments.comment', verbose_name='Parent Comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post', verbose_name='Post')),
                ('translated_by', models.ForeignKey(blank=True, help_text='User who provided the translation, if different from the author.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translated_comments', to=settings.AUTH_USER_MODEL, verbose_name='Translated by')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_made_by', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
