# Generated by Django 5.2.3 on 2025-06-19 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('title_es', models.CharField(max_length=250, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='Title')),
                ('title_ca', models.CharField(max_length=250, null=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug (URL friendly)')),
                ('slug_es', models.SlugField(max_length=250, null=True, unique=True, verbose_name='Slug (URL friendly)')),
                ('slug_en', models.SlugField(max_length=250, null=True, unique=True, verbose_name='Slug (URL friendly)')),
                ('slug_ca', models.SlugField(max_length=250, null=True, unique=True, verbose_name='Slug (URL friendly)')),
                ('content', models.TextField(verbose_name='Content')),
                ('content_es', models.TextField(null=True, verbose_name='Content')),
                ('content_en', models.TextField(null=True, verbose_name='Content')),
                ('content_ca', models.TextField(null=True, verbose_name='Content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
                ('is_homepage', models.BooleanField(default=False, help_text='Mark only one page with this option. If multiple are marked, the most recent one will be used.', verbose_name='Is Homepage?')),
                ('meta_title', models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title (SEO)')),
                ('meta_title_es', models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title (SEO)')),
                ('meta_title_en', models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title (SEO)')),
                ('meta_title_ca', models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title (SEO)')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (SEO)')),
                ('meta_description_es', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (SEO)')),
                ('meta_description_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (SEO)')),
                ('meta_description_ca', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (SEO)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('importance_order', models.PositiveIntegerField(default=99, help_text="A lower number means higher priority in search results. E.g., 1 for 'About Us', 2 for 'Contact', 99 for others.", verbose_name='Importance Order')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('categories', models.ManyToManyField(blank=True, related_name='pages', to='categories.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ['-created_at'],
            },
        ),
    ]
