# Generated by Django 5.2.3 on 2025-06-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/featured/', verbose_name='Featured Image'),
        ),
    ]
