# Generated by Django 5.2.3 on 2025-06-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/featured/%Y/%m/%d/', verbose_name='Imagen Destacada'),
        ),
    ]
