# Generated by Django 5.2.3 on 2025-06-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_content_en_page_content_es_page_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug_en',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='Slug (URL amigable)'),
        ),
        migrations.AddField(
            model_name='page',
            name='slug_es',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='Slug (URL amigable)'),
        ),
    ]
