# Generated by Django 5.2.3 on 2025-06-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_slug_en_page_slug_es'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_es',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
