# Generated by Django 5.2.3 on 2025-06-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_category_description_en_category_description_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_homepage',
            field=models.BooleanField(default=False, help_text='Marcar solo una página con esta opción. Si varias están marcadas, se usará la más reciente.', verbose_name='¿Es la página de inicio?'),
        ),
    ]
