# Generated by Django 5.2.3 on 2025-06-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_page_is_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'categoría de página', 'verbose_name_plural': 'categorías de página'},
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Descripción (SEO)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Descripción (SEO)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Descripción (SEO)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Título (SEO)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Título (SEO)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_es',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Título (SEO)'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Descripción (SEO)'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Descripción (SEO)'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Descripción (SEO)'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Título (SEO)'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Título (SEO)'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title_es',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Título (SEO)'),
        ),
    ]
