# Generated by Django 5.2.3 on 2025-06-16 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_category_options_category_meta_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'page category', 'verbose_name_plural': 'page categories'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-created_at'], 'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (SEO)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (SEO)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (SEO)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title (SEO)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title (SEO)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title_es',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title (SEO)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='page',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='page',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='pages', to='pages.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_es',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_homepage',
            field=models.BooleanField(default=False, help_text='Mark only one page with this option. If multiple are marked, the most recent one will be used.', verbose_name='Is Homepage?'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (SEO)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (SEO)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (SEO)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title (SEO)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title (SEO)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title_es',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title (SEO)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Slug (URL friendly)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug_en',
            field=models.SlugField(max_length=250, null=True, unique=True, verbose_name='Slug (URL friendly)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug_es',
            field=models.SlugField(max_length=250, null=True, unique=True, verbose_name='Slug (URL friendly)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_es',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
    ]
