# Generated by Django 5.2.3 on 2025-06-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_category_options_alter_page_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_ca',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_ca',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (SEO)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_ca',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title (SEO)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ca',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_ca',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_ca',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_ca',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (SEO)'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title_ca',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title (SEO)'),
        ),
        migrations.AddField(
            model_name='page',
            name='slug_ca',
            field=models.SlugField(max_length=250, null=True, unique=True, verbose_name='Slug (URL friendly)'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ca',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
    ]
