# Generated by Django 5.2.3 on 2025-06-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_category_importance_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='importance_order',
        ),
        migrations.AddField(
            model_name='page',
            name='importance_order',
            field=models.PositiveIntegerField(default=99, help_text="A lower number means higher priority in search results. E.g., 1 for 'About Us', 2 for 'Contact', 99 for others.", verbose_name='Importance Order'),
        ),
    ]
