# Generated by Django 5.2.3 on 2025-06-19 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Your full name or a nickname, which will be shown publicly.', max_length=150, verbose_name='Display Name')),
                ('public_email', models.EmailField(blank=True, help_text="An email address you don't mind sharing publicly for contact.", max_length=254, verbose_name='Public Email')),
                ('website_url', models.URLField(blank=True, max_length=255, verbose_name='Website URL')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('avatar', models.ImageField(default='images/avatars/default_private.png', upload_to='avatars/', verbose_name='Avatar')),
                ('default_avatar_choice', models.CharField(choices=[('images/avatars/default_private.png', "Don't specify"), ('images/avatars/default_female.png', 'Female'), ('images/avatars/default_male.png', 'Male'), ('images/avatars/default_nonbinary.png', 'Non-binary')], default='images/avatars/default_private.png', max_length=100, verbose_name='Default Avatar Preference')),
                ('is_trusted_commenter', models.BooleanField(default=False, help_text='If checked, comments are automatically approved.', verbose_name='Is a Trusted Commenter?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
