# Generated by Django 5.2.3 on 2025-06-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_listed_publicly',
            field=models.BooleanField(default=True, help_text='If checked, your profile will be visible in the public user directory.', verbose_name='List profile publicly?'),
        ),
    ]
