# Generated by Django 5.2.3 on 2025-06-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_listed_publicly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_listed_publicly',
            field=models.BooleanField(default=False, help_text='If checked, your profile will be visible in the public user directory.', verbose_name='List profile publicly?'),
        ),
    ]
