# Generated by Django 5.2.3 on 2025-06-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_trusted_commenter',
            field=models.BooleanField(default=False, help_text='If checked, comments are automatically approved.', verbose_name='Is a Trusted Commenter?'),
        ),
    ]
