# Generated by Django 5.2.3 on 2025-06-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_es',
            field=models.TextField(null=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_en',
            field=models.SlugField(max_length=250, null=True, unique_for_date='published_date', verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_es',
            field=models.SlugField(max_length=250, null=True, unique_for_date='published_date', verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es',
            field=models.CharField(max_length=250, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='name_es',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='slug_en',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='slug_es',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
