# Generated by Django 5.2.3 on 2025-06-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_content_en_post_content_es_post_slug_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Descripción (SEO)'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Descripción (SEO)'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Descripción (SEO)'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Título (SEO)'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Título (SEO)'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title_es',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Título (SEO)'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Descripción (SEO)'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Descripción (SEO)'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Descripción (SEO)'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Título (SEO)'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Título (SEO)'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='meta_title_es',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Título (SEO)'),
        ),
    ]
