# Generated by Django 5.2.3 on 2025-06-16 16:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_meta_description_post_meta_description_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published_date',), 'verbose_name': 'blog post', 'verbose_name_plural': 'blog posts'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'ordering': ['name'], 'verbose_name': 'blog category', 'verbose_name_plural': 'blog categories'},
        ),
        migrations.AddField(
            model_name='post',
            name='content_ca',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description_ca',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (SEO)'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title_ca',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title (SEO)'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_ca',
            field=models.SlugField(max_length=250, null=True, unique_for_date='published_date', verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ca',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='meta_description_ca',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (SEO)'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='meta_title_ca',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title (SEO)'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='name_ca',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='slug_ca',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.postcategory', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_es',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/featured/%Y/%m/%d/', verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (SEO)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (SEO)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (SEO)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title (SEO)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title (SEO)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_title_es',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title (SEO)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_es',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (SEO)'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (SEO)'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (SEO)'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title (SEO)'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title (SEO)'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='meta_title_es',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title (SEO)'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name_es',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
    ]
