# Generated by Django 5.2.3 on 2025-06-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_content_ca_comment_content_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is Approved?'),
        ),
    ]
