# Generated by Django 5.2.3 on 2025-06-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Author Email'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Author Name'),
        ),
    ]
