# Generated by Django 5.2.3 on 2025-06-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_comment_author_email_alter_comment_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editor_rating',
            field=models.PositiveIntegerField(default=0, help_text='A score from 0-100 to feature this post. Higher numbers appear first.', verbose_name="Editor's Rating"),
        ),
    ]
