# Generated by Django 5.2.3 on 2025-06-19 21:04

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='An optional description for the category.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_ca',
            field=models.TextField(blank=True, help_text='An optional description for the category.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, help_text='An optional description for the category.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_es',
            field=models.TextField(blank=True, help_text='An optional description for the category.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, help_text='A short description for search engine previews (max 160 chars).', max_length=160, null=True, verbose_name='Meta Description (SEO)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='A precise title for search engine results (max 70 chars).', max_length=70, null=True, verbose_name='Meta Title (SEO)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Select a parent to create a sub-category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category', verbose_name='Parent Category'),
        ),
    ]
