# Generated by Django 5.2.3 on 2025-07-01 20:43

import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_category_options_alter_category_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(blank=True, max_length=100, null=True, verbose_name='DOI')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='publications/featured/', verbose_name='Cover Image')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='publications/files/', verbose_name='Full PDF')),
                ('publication_date', models.DateField(default=django.utils.timezone.now, verbose_name='Publication Date')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('authors', models.ManyToManyField(related_name='publications', to=settings.AUTH_USER_MODEL, verbose_name='Authors')),
                ('categories', models.ManyToManyField(blank=True, related_name='publications', to='categories.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-publication_date'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PublicationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(max_length=250, verbose_name='Slug')),
                ('abstract', models.TextField(blank=True, verbose_name='Abstract')),
                ('content', tinymce.models.HTMLField(verbose_name='Full Content')),
                ('meta_title', models.CharField(blank=True, max_length=70, null=True, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='publications.publication')),
            ],
            options={
                'verbose_name': 'Publication Translation',
                'db_table': 'publications_publication_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
