# Generated by Django 5.2.3 on 2025-06-19 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Zone Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (used in templates)')),
            ],
            options={
                'verbose_name': 'Widget Zone',
                'verbose_name_plural': 'Widget Zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('recent_posts', 'Recent Blog Posts'), ('most_viewed_posts', 'Most Viewed Blog Posts'), ('most_commented_posts', 'Most Commented Blog Posts'), ('blog_categories', 'Blog Category List'), ('editor_picks_posts', "Editor's Picks (Blog Posts)")], max_length=50, verbose_name='Widget Type')),
                ('title', models.CharField(help_text='The title that will be displayed above the widget.', max_length=100, verbose_name='Widget Title')),
                ('title_es', models.CharField(help_text='The title that will be displayed above the widget.', max_length=100, null=True, verbose_name='Widget Title')),
                ('title_en', models.CharField(help_text='The title that will be displayed above the widget.', max_length=100, null=True, verbose_name='Widget Title')),
                ('title_ca', models.CharField(help_text='The title that will be displayed above the widget.', max_length=100, null=True, verbose_name='Widget Title')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('item_count', models.PositiveIntegerField(default=5, help_text="Used by widgets that display a list of items, like 'Recent Posts' or 'Blog Categories'.", verbose_name='Number of items to show')),
                ('cache_timeout', models.PositiveIntegerField(default=900, help_text='How long the results of this widget should be stored in cache. 0 to disable caching for this widget.', verbose_name='Cache Timeout (in seconds)')),
                ('category_filter', models.ForeignKey(blank=True, help_text='If selected, the widget will only show items from this specific category.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name='Filter by Category (optional)')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='widgets.widgetzone', verbose_name='Widget Zone')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['zone', 'order'],
            },
        ),
    ]
