# Generated by Django 5.2.3 on 2025-06-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='item_count',
            field=models.PositiveIntegerField(default=5, help_text="Used by widgets that display a list of items, like 'Recent Posts' or 'Blog Categories'.", verbose_name='Number of items to show'),
        ),
    ]
