# Generated by Django 5.2.3 on 2025-06-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='column_count',
            field=models.PositiveIntegerField(default=3, help_text='Number of columns for grid display (e.g., 2, 3, 4).', verbose_name='Column Count'),
        ),
        migrations.AddField(
            model_name='widget',
            name='section_title',
            field=models.CharField(blank=True, help_text="A main title for this grid section (e.g., 'Latest Posts', 'Our Bestsellers').", max_length=200, null=True, verbose_name='Section Title (Optional)'),
        ),
        migrations.AddField(
            model_name='widget',
            name='view_all_link_text',
            field=models.CharField(blank=True, help_text="Text for the 'View All' link below the grid (e.g., 'View All Posts').", max_length=100, null=True, verbose_name='View All Link Text'),
        ),
        migrations.AddField(
            model_name='widget',
            name='view_all_link_url',
            field=models.CharField(blank=True, help_text="URL for the 'View All' link (e.g., '/blog/').", max_length=255, null=True, verbose_name='View All Link URL'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('recent_posts', 'Recent Blog Posts'), ('most_viewed_posts', 'Most Viewed Blog Posts'), ('most_commented_posts', 'Most Commented Blog Posts'), ('blog_categories', 'Blog Category List'), ('editor_picks_posts', "Editor's Picks (Blog Posts)"), ('post_grid_recent', 'Post Grid: Recent Posts'), ('post_grid_popular', 'Post Grid: Most Viewed'), ('post_grid_commented', 'Post Grid: Most Commented'), ('post_grid_editor', "Post Grid: Editor's Picks")], max_length=50, verbose_name='Widget Type'),
        ),
    ]
