# Generated by Django 5.2.3 on 2025-06-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0003_alter_widget_widget_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='cache_timeout',
            field=models.PositiveIntegerField(default=900, help_text='How long the results of this widget should be stored in cache. 0 to disable caching for this widget.', verbose_name='Cache Timeout (in seconds)'),
        ),
    ]
