# Generated by Django 5.2.3 on 2025-06-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_posts_per_page', models.PositiveIntegerField(default=6, verbose_name='Posts per Page in Blog')),
                ('search_results_per_page', models.PositiveIntegerField(default=5, verbose_name='Results per Page in Search')),
                ('recent_posts_widget_count', models.PositiveIntegerField(default=5, verbose_name="Number of Posts in 'Recent Posts' Widget")),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
