# Generated by Django 5.2.3 on 2025-06-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='popular_posts_widget_count',
            field=models.PositiveIntegerField(default=5, verbose_name="Number of Posts in 'Most Viewed' Widget"),
        ),
    ]
