# Generated by Django 5.2.3 on 2025-06-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_siteconfiguration_popular_posts_widget_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='comment_indentation_pixels',
            field=models.PositiveIntegerField(default=20, help_text='Controls how much space is added for each level of nested comments in the admin list view.', verbose_name='Comment Indentation (in pixels)'),
        ),
    ]
