# Generated by Django 5.2.3 on 2025-06-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_siteconfiguration_category_tree_cache_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='gallery_items_per_page',
            field=models.PositiveIntegerField(default=9, help_text='Number of images to show on the image gallery page.', verbose_name='Items per Page in Gallery'),
        ),
    ]
