# Generated by Django 5.2.3 on 2025-06-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_siteconfiguration_comment_indentation_pixels'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='auto_approve_comments',
            field=models.BooleanField(default=False, help_text='If checked, new comments will be published immediately without moderation.', verbose_name='Auto-approve comments'),
        ),
    ]
