# Generated by Django 5.2.3 on 2025-06-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_siteconfiguration_gallery_items_per_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='user_profile_items_per_page',
            field=models.PositiveIntegerField(default=5, help_text="Number of posts/comments to show per page on a user's public profile.", verbose_name='Items per Page on Public Profile'),
        ),
    ]
