# Generated by Django 5.2.3 on 2025-06-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_siteconfiguration_auto_approve_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='blog_posts_per_page',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='blog_items_per_page',
            field=models.PositiveIntegerField(default=9, verbose_name='Items per Page in Blog/Category lists'),
        ),
    ]
