# Generated by Django 5.2.3 on 2025-06-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_remove_siteconfiguration_blog_posts_per_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='search_importance_limit',
            field=models.PositiveIntegerField(default=3, help_text='How many top-priority pages to display before regular search results.', verbose_name="Number of 'Important' Pages to show first in search"),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='blog_items_per_page',
            field=models.PositiveIntegerField(default=9, help_text='Number of posts to show on the main blog page and on category pages.', verbose_name='Items per Page in Blog/Category lists'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='comment_indentation_pixels',
            field=models.PositiveIntegerField(default=20, help_text='Controls the visual indentation for nested comments in the admin.', verbose_name='Comment Indentation (in pixels)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='search_results_per_page',
            field=models.PositiveIntegerField(default=5, help_text='Number of items to show per section (Pages/Posts) on the search results page.', verbose_name='Results per Page in Search'),
        ),
    ]
