# Generated by Django 5.2.3 on 2025-06-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_siteconfiguration_search_importance_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='search_pages_per_page',
            field=models.PositiveIntegerField(default=5, verbose_name='Pages per Page in Search Results'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='search_posts_per_page',
            field=models.PositiveIntegerField(default=5, verbose_name='Posts per Page in Search Results'),
        ),
    ]
