# Generated by Django 5.2.3 on 2025-06-17 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_siteconfiguration_search_pages_per_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='popular_posts_widget_count',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='recent_posts_widget_count',
        ),
    ]
