# Generated by Django 5.2.3 on 2025-06-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_remove_siteconfiguration_popular_posts_widget_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='The main logo displayed in the top bar.', null=True, upload_to='site_branding/', verbose_name='Site Logo'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_slogan',
            field=models.CharField(blank=True, help_text='A short tagline displayed next to the logo.', max_length=150, verbose_name='Site Slogan'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_slogan_ca',
            field=models.CharField(blank=True, help_text='A short tagline displayed next to the logo.', max_length=150, null=True, verbose_name='Site Slogan'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_slogan_en',
            field=models.CharField(blank=True, help_text='A short tagline displayed next to the logo.', max_length=150, null=True, verbose_name='Site Slogan'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_slogan_es',
            field=models.CharField(blank=True, help_text='A short tagline displayed next to the logo.', max_length=150, null=True, verbose_name='Site Slogan'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='top_bar_banner_image',
            field=models.ImageField(blank=True, help_text='An optional banner image displayed in the top bar.', null=True, upload_to='site_branding/banners/', verbose_name='Top Bar Banner Image'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='top_bar_banner_link',
            field=models.URLField(blank=True, help_text='The URL the banner image will link to.', max_length=255, verbose_name='Top Bar Banner Link'),
        ),
    ]
