# Generated by Django 5.2.3 on 2025-06-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_siteconfiguration_site_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='menu_cache_timeout',
            field=models.PositiveIntegerField(default=3600, help_text='How long the site menus should be stored in cache. Set to 0 to disable menu caching (not recommended).', verbose_name='Menu Cache Timeout (in seconds)'),
        ),
    ]
