# Generated by Django 5.2.3 on 2025-06-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0010_siteconfiguration_menu_cache_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='trusted_commenter_threshold',
            field=models.PositiveIntegerField(default=10, help_text='The number of approved comments a user needs to post before their future comments are auto-approved.', verbose_name='Trusted Commenter Threshold'),
        ),
    ]
