# Generated by Django 5.2.3 on 2025-06-15 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Texto del Enlace')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('link_url', models.CharField(blank=True, help_text='Usa esto para URLs externas (ej: https://google.com) o rutas manuales (ej: /blog/).', max_length=255, verbose_name='Enlazar a una URL manual')),
                ('link_page', models.ForeignKey(blank=True, help_text='Selecciona una página interna para enlazar. Deja en blanco si usas una URL manual.', null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page', verbose_name='Enlazar a una Página')),
            ],
            options={
                'verbose_name': 'Elemento de Menú',
                'verbose_name_plural': 'Elementos de Menú',
                'ordering': ['order'],
            },
        ),
    ]
