# Generated by Django 5.2.3 on 2025-06-19 22:24

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Menu Title')),
                ('title_es', models.CharField(max_length=100, null=True, unique=True, verbose_name='Menu Title')),
                ('title_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='Menu Title')),
                ('title_ca', models.CharField(max_length=100, null=True, unique=True, verbose_name='Menu Title')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Link Text')),
                ('title_es', models.CharField(max_length=100, null=True, verbose_name='Link Text')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Link Text')),
                ('title_ca', models.CharField(max_length=100, null=True, verbose_name='Link Text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('link_type', models.CharField(choices=[('url', 'Manual URL'), ('page', 'Single Page'), ('all_blog_categories', 'Blog Categories Tree (Dropdown)'), ('important_pages', 'Important Pages List (Dropdown)')], default='url', max_length=50, verbose_name='Link Type')),
                ('link_url', models.CharField(blank=True, max_length=255, verbose_name='Manual URL')),
                ('icon_class', models.CharField(blank=True, max_length=100, verbose_name='Icon Class')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.page', verbose_name='Page Link')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.menu', verbose_name='Menu')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menus.menuitem', verbose_name='Parent Menu Item')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
            },
        ),
    ]
