# Generated by Django 5.2.3 on 2025-06-19 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Menu Title')),
                ('title_es', models.CharField(max_length=100, null=True, unique=True, verbose_name='Menu Title')),
                ('title_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='Menu Title')),
                ('title_ca', models.CharField(max_length=100, null=True, unique=True, verbose_name='Menu Title')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (identifier for code)')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Link Text')),
                ('title_es', models.CharField(max_length=100, null=True, verbose_name='Link Text')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Link Text')),
                ('title_ca', models.CharField(max_length=100, null=True, verbose_name='Link Text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('link_url', models.CharField(blank=True, help_text='Use for external URLs (e.g., https://google.com) or fixed paths (e.g., /blog/).', max_length=255, verbose_name='Link to a manual URL')),
                ('icon_class', models.CharField(blank=True, max_length=100, null=True, verbose_name='Icon Class (e.g., fab fa-facebook)')),
                ('link_page', models.ForeignKey(blank=True, help_text='Select an internal page to link to. Leave blank if using a manual URL.', null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page', verbose_name='Link to a Page')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.menu', verbose_name='Menu it belongs to')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['order'],
            },
        ),
    ]
