# Generated by Django 5.2.3 on 2025-06-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Texto del Enlace'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Texto del Enlace'),
        ),
    ]
