# Generated by Django 5.2.3 on 2025-06-15 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menuitem_title_en_menuitem_title_es'),
        ('pages', '0007_page_is_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Título del Menú')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (identificador para el código)')),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menús',
            },
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_page',
            field=models.ForeignKey(blank=True, help_text='Selecciona una página interna. Deja en blanco si usas una URL manual.', null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page', verbose_name='Enlazar a una Página'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_url',
            field=models.CharField(blank=True, help_text='Úsalo para URLs externas (ej: https://google.com) o rutas fijas (ej: /blog/).', max_length=255, verbose_name='Enlazar a una URL manual'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.menu', verbose_name='Menú al que pertenece'),
        ),
    ]
