# Generated by Django 5.2.3 on 2025-06-16 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_menu_alter_menuitem_link_page_and_more'),
        ('pages', '0009_alter_category_options_alter_page_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order'], 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AddField(
            model_name='menu',
            name='title_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Menu Title'),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_es',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Menu Title'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='icon_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Icon Class (e.g., fab fa-facebook)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug (identifier for code)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Menu Title'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_page',
            field=models.ForeignKey(blank=True, help_text='Select an internal page to link to. Leave blank if using a manual URL.', null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page', verbose_name='Link to a Page'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_url',
            field=models.CharField(blank=True, help_text='Use for external URLs (e.g., https://google.com) or fixed paths (e.g., /blog/).', max_length=255, verbose_name='Link to a manual URL'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.menu', verbose_name='Menu it belongs to'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Link Text'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Link Text'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Link Text'),
        ),
    ]
