# Generated by Django 5.2.3 on 2025-06-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_alter_menu_options_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='title_ca',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Menu Title'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_ca',
            field=models.CharField(max_length=100, null=True, verbose_name='Link Text'),
        ),
    ]
